[book]
authors = ["UCloud authors"]
language = "en"
multilingual = false
src = "src"
title = "UCloud"

[preprocessor.external-links]

[output.html]
default-theme = "light"
preferred-dark-theme = "dark"

[output.html.print]
enable = false

[build]
create-missing = false