---
apiVersion: v1
kind: Service
metadata:
  name: share
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: shares
      prefix: ^/api/shares(/.*)?$
      prefix_regex: true
      service: share:8080
      rewrite: ""

      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: share_list_files
      prefix: ^/api/shares/list-files$
      prefix_regex: true
      rewrite: ""
      service: share:8080
      method: GET
      precedence: 10
      headers:
        x-no-load: true

spec:
  clusterIP: None
  type: ClusterIP
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: share-service
