provider:
  id: k8s

  hosts:
    ucloud:
      address: core2
      port: 8080
      scheme: http
    self:
      address: k8s
      port: 8889
      scheme: http
    selfPublic:
      address: k8s.localhost.direct
      port: 443
      scheme: https
    ucloudPublic:
      address: ucloud.localhost.direct
      port: 443
      scheme: https

  ipc:
    directory: /var/run/ucloud

  logs:
    directory: /var/log/ucloud
    rotation:
      enabled: true
      retentionPeriodInDays: 180

  envoy:
    directory: /var/run/ucloud/envoy
    executable: /usr/bin/envoy
    funceWrapper: false

services:
  type: Kubernetes
  compute:
    web:
      enabled: true
      prefix: "k8s-"
      suffix: ".localhost.direct"

    publicLinks:
      enabled: true
      prefix: "k8s-"
      suffix: ".localhost.direct"

    publicIps:
      enabled: true

    integratedTerminal:
      enabled: true

    syncthing:
      enabled: true
      ipAddress: 10.56.32.4
      portMin: 8000
      portMax: 16000
      relaysEnabled: false

    ssh:
      enabled: true
      ipAddress: 10.56.32.3
      hostname: ucloud.invalid
      portMin: 8000
      portMax: 16000

    modules:
      "ubuntu-22.04":
        subPath: "modules"
        claimName: cephfs
      "almalinux-8":
        subPath: "modules"
        claimName: cephfs
      "colabfold":
        subPath: "modules"
        claimName: cephfs
      "alphafold3":
        subPath: "modules"
        claimName: cephfs
      "ubuntu-24.04":
        subPath: "modules"
        claimName: cephfs
      "almalinux-9":
        subPath: "modules"
        claimName: cephfs

    machines:
      u1-standard:
        nameSuffix: Cpu

        cpu: [ 1, 2, 4 ]
        memory: [ 1, 2, 4 ]

        cpuModel: Model
        memoryModel: Model

        payment:
          type: Resource
          unit: Cpu
          interval: Minutely

  fileSystem:
    name: storage
    mountPoint: /mnt/storage
    trashStagingArea: /mnt/storage/trash
    claimName: cephfs
