---
apiVersion: v1
kind: Service
metadata:
  name: app-store
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: app-store
      prefix: ^/api/hpc(/.*)?$
      prefix_regex: true
      service: app-store:8080
      rewrite: ""
      timeout_ms: 0

spec:
  clusterIP: None
  type: ClusterIP
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: app-store
